install:
  npx pnpm -r install

build:
  npx pnpm -r install
  npx pnpm -r build

test:
  npx pnpm -r test

update-deps:
  npx pnpm -r exec npx npm-check-updates -u

clean:
  rm -rf packages/*/node_modules
  rm -rf node_modules